
```{r functions, include=FALSE}
## Custom functions used in the analysis should go into this chunk.
## They will be listed in their own section of the appendix.
myGetMgrastAnnotation<-function(MetagenomeID, evalue = 5, identity = 60, length = 15, 
                                 resource = c(source = "KO", type = "ontology"), webkey){
  MetagenomeID <- paste0("mgm", MetagenomeID)
  server.resource <- "http://api.metagenomics.anl.gov/1/annotation/similarity/"
  server.resource <- paste0(server.resource, MetagenomeID)
  message(paste("Loading the annotations form MG-RAST of", 
                MetagenomeID), domain = NA)
  message("The time spent in this step is proportional to the total amount of remote data...")
  param <- list(source = resource["source"], type = resource["type"], 
                evalue = evalue, identity = identity, length = length, 
                auth = webkey)
  anno <- tryCatch(getForm(server.resource, .params = param, 
                           .opts = list(noprogress = FALSE, 
                                        progressfunction = function(down,up) {
                             cat(paste("\r", 
                                       "loading", 
                                       paste0(round(down[2]/1024^2,2), "MB"),
                                       "..."))
                             flush.console()
                           })), error = function(e) {
                             msg <- conditionMessage(e)
                             structure(msg, class = "try-error")
                           })
  if (inherits(anno, "try-error")) {
    warning(anno)
    return(FALSE)
  }
  invalid.source <- which(grepl("Invalid\\s+ontology\\s+source", 
                                anno))
  if (length(invalid.source)) 
    stop("invalid ontology source")
  if (length(which(grepl("insufficient\\s+permissions", 
                         anno)))) 
    stop("invalid webkey")
  anno <- read.delim(textConnection(anno), header = FALSE, 
                     sep = "\t", stringsAsFactor = F)
  return(anno)
  cat("\n", MetagenomeID, "annotation data loading completed")
}
getAnnotationFromFile<-function(file){
  l<-readLines(file)
  if(!grepl("Download\\s+complete", l[length(l)])){
    stop('Download is incomplete')
  }
  anno<-read.delim(file, header = FALSE, fill=TRUE,  sep = "\t", stringsAsFactor = F)
  anno[nrow(anno)+1,1]<-'Download complete'
  return(anno)
}
mergeAnnots<-function(f,s){
  keycols<-names(f)[1:12]
setkeyv(f,keycols)
setkeyv(s,keycols)
  d.merge<-merge(f,s,all=TRUE,suffixes = c('.fun','.sp'))
  names(d.merge)<-gsub('semicolon separated list of annotations.','',names(d.merge))
  return(d.merge)  
}
expandNamesDT<-function(d.merge){
  d<-d.merge[,.(`query sequence id`,`hit m5nr id (md5sum)`,fun,sp)]
  names(d)<-c('id','md5sum','fun','sp')
  #dt[ , list( pep = unlist( strsplit( pep , ";" ) ) ) , by = pro ]
unique(d[ , list(ufun = gsub('(\\]|\\[)','',unlist( strsplit( fun, "\\]; *\\[" ) )) ,fun,sp,ab=.N) , by = md5sum ])->d.ufun
unique(d.ufun[ , list(fun,usp=gsub('(\\]|\\[)','',unlist( strsplit( sp, "\\]; *\\[" ) )) ,sp,ab) , by = .(md5sum,ufun) ])->d.uspfun
  return(d.uspfun)
}
getAbundanceFromDT<-function(d.ab){
  d.ab<-d.ab[,sum:=sum(ab),by=.(usp,ufun)]
  d.ab<-unique(d.ab[,.(usp,ufun,sum)])
  return(d.ab)
}
getAbundanceMD5FromDT<-function(d.ab){
  d.ab<-d.ab[,.(sum=sum(ab),md5=paste(md5sum,collapse = ',')),by=.(usp,ufun)]
  d.ab<-unique(d.ab[,.(usp,ufun,sum,md5)])
  return(d.ab)
}
getSpecieFromAbund<-function(d.bm,sp='Geobacter',aggregate=FALSE){
  d.res<-d.bm[grep(sp,d.bm$usp),]
  if(aggregate&dim(d.res)[1]>1) d.res<-aggregate(.~ufun,as.data.frame(d.res)[,-1],FUN = sum)
  return(d.res)
}
getFunctionFromAbund<-function(d.bm,fun='protein',aggregate=FALSE){
  d.res<-d.bm[grep(fun,d.bm$ufun),]
  if(aggregate&dim(d.res)[1]>1) d.res<-aggregate(.~usp,as.data.frame(d.res)[,-2],FUN = sum)
  return(d.res)
}
getSpecieFromAbundMD5<-function(d.bm,sp='Geobacter',aggregate=FALSE){
  d.res<-d.bm[grep(sp,d.bm$usp),]
  if(aggregate&dim(d.res)[1]>1) d.res<-aggregate(.~ufun,as.data.frame(d.res)[,-c(1,3)],FUN = sum)
  return(d.res)
}
getFunctionFromAbundMD5<-function(d.bm,fun='protein',aggregate=FALSE){
  d.res<-d.bm[grep(fun,d.bm$ufun),]
  if(aggregate&dim(d.res)[1]>1) d.res<-aggregate(.~usp,as.data.frame(d.res)[,-c(2,3)],FUN = sum)
  return(d.res)
}
returnAppropriateObj<-function(obj, norm, log){
  if(class(obj)!='matrix') stop('Obj should be a matrix')
  res<-obj
  if(log){
    res<-log2(res+1)
  }
  if(norm){
    res<-scale(res)
  }
  return(res)
}
plotHeatmap<-function(obj,n,norm=TRUE,log=TRUE,fun=sd,...){
   mat = returnAppropriateObj(obj, norm, log)
  otusToKeep = which(rowSums(mat) > 0)
  if(length(otusToKeep)==1){
    otuStats<-fun(mat)
  }else{  
    otuStats = apply(mat[otusToKeep, ], 1, fun)
  }
  otuIndices = otusToKeep[order(otuStats, decreasing = TRUE)[1:min(c(n,dim(mat)[1]))]]
  mat2 = mat[otuIndices, ]
  heatmap.2(mat2, hclustfun = function(.x)hclust(.x,method = 'ward.D2'),srtCol=45,
            key.title=NA,
            key.xlab=NA,
            key.par=list(mgp=c(1.5, 0.5, 0),
                         mar=c(1, 2.5, 1, 0.5)),
            lmat=rbind( c(0, 3, 4), c(2,1,0 ) ),
            lwid=c(1.5, 4, 1.5 ),...)

            #srtRow=45,...)
  invisible(mat2)

}
plotSP<-function(d3,sp){
  d<-getSpecieFromAbund(d3,sp = sp,aggregate = FALSE)
d.sp<-aggregate(.~usp,as.data.frame(d)[,-2],FUN = sum)
obj<-as.matrix(d.sp[,-1])
rownames(obj)<-d.sp$usp
colnames(obj)<-mdt$MGN
if(dim(obj)[1]>1){
res<-plotHeatmap(obj,50,trace = "none", col = heatmapCols,main=paste(sp,'\n log-transformed'),norm=FALSE)
}else{
  res<-returnAppropriateObj(obj,norm = FALSE,log = TRUE)
}
invisible(res)
}

showTable<-function(obj,main,landscape=TRUE){
  mat<-as.matrix(obj)
  mat<-mat[order(rowSums(mat),decreasing = TRUE),]
      addtorow          <- list()
    addtorow$pos      <- list()
    addtorow$pos[[1]] <- c(0)
    addtorow$command  <- c(paste("\\hline \n",
                                 "\\endhead \n",
                                 "\\hline \n",
                                 "\\multicolumn{3}{l}{\\footnotesize Continued on next page} \n",
                                 "\\endfoot \n",
                                 "\\endlastfoot \n",sep=""))
    if(landscape){
      cat(sprintf("\\newpage\n \\begin{landscape} \n\\begin{center}\n\\captionof{table}{Summary %s }\n\\scriptsize",main))
    }else{
      cat(sprintf("\\newpage \n\\begin{center}\n\\captionof{table}{Summary %s }\n\\scriptsize",main))
    }
    ind<-1:length(colnames(mat))
    alig<-c('p{5cm}',rep('r',length(ind)))
    
    print(xtable(mat[,order(colnames(mat))[ind]], 
                 align = paste(alig,collapse = ''),digits = 2)
          ,size="small",include.colnames = TRUE,
          tabular.environment="longtable",
          floating=FALSE,include.rownames=TRUE,
          add.to.row = addtorow,hline.after=c(-1))
    if(landscape){
      cat("\\end{center}\n \\end{landscape}")
    }else{
      cat("\\end{center}\n ")
    }
}
```

# Loading required data
```
{r access.key, include=FALSE,echo=FALSE}
key='y8MLy5NRMBfCRGzPcxYP9b86c'
keyDate<-"2016 11-13 20:02.00"
if(as.Date(keyDate,format="%Y %m-%d %H:%M.%S")<Sys.Date()) stop('New Key has to be generated')
```

```{r load.metadata}
mdt<-read.delim(file = 'jobs.tsv')
mdt$Name<-sub('^[0-9]+_([^_]+)_[^_]+_([^_]+).*$','\\1_\\2',mdt$Metagenome.Name)
mdt$EID<-sub('^([^_]+)_.*$','\\1',mdt$Name)
mdt$MFCID<-NA
mdt$MFCID[mdt$EID=='S5'|mdt$EID=='S6']<-'MFC1_p'
mdt$MFCID[mdt$EID=='S7'|mdt$EID=='S8']<-'MFC3_p'
mdt$MFCID[mdt$EID=='S9'|mdt$EID=='S10']<-'MFC1_a'
mdt$MFCID[mdt$EID=='S11'|mdt$EID=='S12']<-'MFC3_a'
mdt$MFCID[mdt$EID=='S9'|mdt$EID=='S10']<-'MFC1_a'
mdt$MFCID[mdt$EID=='S11'|mdt$EID=='S12']<-'MFC3_a'
mdt$MFCID[mdt$EID=='S1']<-'inflowSW'
mdt$MFCID[mdt$EID=='S2']<-'rIS'
mdt$MFCID[mdt$EID=='S3']<-'rSW'
mdt$MFCID[mdt$EID=='S4']<-'sMiz'
mdt$Source<-NA
samplesToKeep<-grep('_a',mdt$MFCID)
mdt$Source[samplesToKeep]<-'anode'
samplesToKeep<-grep('_p',mdt$MFCID)
mdt$Source[samplesToKeep]<-'plankton'
samplesToKeep<-grep('^r',mdt$MFCID)
mdt$Source[samplesToKeep]<-'inoculum'
samplesToKeep<-grep('^inflow',mdt$MFCID)
mdt$Source[samplesToKeep]<-'inflow'
mdt$Origin<-NA
samplesToKeep<-grep('S(3|5|9|6|10)',mdt$Metagenome.Name)
mdt$Origin[samplesToKeep]<-'sws'
samplesToKeep<-grep('S(2|7|11|8|12)',mdt$Metagenome.Name)
mdt$Origin[samplesToKeep]<-'is'
mdt$Origin[mdt$MFCID=="inflowSW"]<-'inflow'
rownames(mdt) <- as.character(mdt[, 1])
heatmapCols = colorRampPalette(brewer.pal(9, "RdBu"))(50)

```

